[tool.poetry]
name = "Product"
version = "0.1.0"
description = "A FastAPI project with Keycloak integration"
authors = ["Your Name <you@example.com>"]
license = "MIT"





[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
