
spring:
  application:
    name: account

  profiles:
    active: ${ACTIVE_PROFILE:dev}

  datasource:
    url: jdbc:${MYSQL_URL:}://${DATABASE_HOST:}:${MYSQL_PORT}/${DATABASE_DB}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DRIVER_CLASS_NAME}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT}/realms/GentleCorp-Ecosystem

  ssl:
    bundle:
      pem:
        microservice:
          reload-on-update: true
          keystore:
            private-key-password: "gentlecorp11.09.24"
            private-key: "${KEYS_PATH}/key.pem"
            certificate: "${KEYS_PATH}/certificate.crt"
          truststore:
            certificate: "${KEYS_PATH}/certificate.crt"


com:
  c4-soft:
    springaddons:
      oidc:
        ops:
          - iss: http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT}/realms/GentleCorp-Ecosystem
            authorities:
            # Pfad zu den Rollen innerhalb vom "JWT Claim" und zusaetzlicher Praefix "ROLE_" fuer Spring Security
            - path: $.realm_access.roles
              prefix: ROLE_

app:
  keycloak:
    client-secret: FiAT2ma40CGVmctDNOOG9h1XtlAqA7Vb
    #schema: http
    host: ${KEYCLOAK_HOST}
    port: ${KEYCLOAK_PORT}
    client-id: gentlecorp-client
  #logfile: ./build/log/application.log
  password: p
  #password-falsch: FALSCH


server:
  port: ${SERVER_PORT}
