 --------------------------------------------------------
 E i g e n e   P r o p e r t i e s
 --------------------------------------------------------
app.mail:
  from: Theoh Test <theo@test.de>
  sales: hmm Musterfrau <maxi.musterfrau@testd.de>