# ==============================================================================
# N o d e
# ==============================================================================
node:
  port: 8085

# ==============================================================================
# D a t e n b a n k
# ==============================================================================

db:
  type: postgres

  #host: localhost

  username: order_db_user
  password: GentleCorp21.08.2024
  populate: true

  host: localhost
  database: order_db

  adminUsername: root
  passwordAdmin: p

# ==============================================================================
# K A F K A
# ==============================================================================
kafka:
  host: localhost
  
# ==============================================================================
# K e y c l o a k
# ==============================================================================
keycloak:
  authServerUrl: http://localhost:8880
  realm: GentleCorp-Ecosystem
  clientId: gentlecorp-client
  tokenValidation: online

# ==============================================================================
# L o g g i n g
# ==============================================================================
log:
  level: debug
  #dir: ./log
  pretty: true

# ==============================================================================
# H e a l t h
# ==============================================================================
health:
  prettyPrint: true

# ==============================================================================
# J W T
# ==============================================================================
# 1d = 1 Tag, 1h = 1 Stunde, 1m = 1 Minute, 1s = 1 Sekunde
#jwt:
#  expiresIn: 1h
#  issuer: https://hka.de/JuergenZimmermann

# ==============================================================================
# M a i l s e r v e r
# ==============================================================================
mail:
  #activated: false
  host: localhost
  port: 5025
  log: false

# ==============================================================================
# T e s t s
# ==============================================================================
#test:
#  startDbServer: false
